WIP: Decompile PAD
riidefi/mkw pull request #20
Opened 2021-07-01 00:39 UTC by wait-wtf

2021-07-01 22:37 UTC, wait-wtf commented
@riidefi Could you help me out with PADRead()? I'm having an issue with inlining that I can't figure out myself. Might have another look on Saturday.

2021-07-01 22:43 UTC, riidefi commented
> @riidefi Could you help me out with PADRead()? I'm having an issue with inlining that I can't figure out myself. Might have another look on Saturday.
I'll take a look tomorrow, let's make sure we're using the proper compiler version, too.

2021-07-03 06:20 UTC, wait-wtf commented
PADRead() is fixed now by using the `__abs()` compiler intrinsic. PAD_OnReset remains broken.

2021-07-11 06:46 UTC, wait-wtf commented
PAD is now fully decompiled and working.

2021-07-11 12:20 UTC, riidefi requested changes

2021-07-11 12:20 UTC, riidefi commented on source/rvl/pad/rvlPad.c
> +u16 oslow_30e0 : (0x800030e0);
memest/memcpy -> string.h
OS* can go in "osMisc.h" or something now, we can sort them later.

2021-07-11 12:30 UTC, merged