RevoEx SO, GameSpy library
riidefi/mkw pull request #24
Opened 2021-07-03 18:02 UTC by wait-wtf

- [ ] SOFinish

Requires #22, #23

2021-07-11 06:01 UTC, wait-wtf commented
@riidefi This was about as far as I could push it. It's ready for review now.

2021-07-11 12:15 UTC, riidefi requested changes
Incredible work. Just a few notes. :)

2021-07-11 12:15 UTC, snailspeed3 commented on mkwutil/gen_lcf.py
> +            if obj_path.stem in stripped:
Good. Hopefully as the project progresses we can naturally rely on the linker deadstripping more and more.

2021-07-11 12:15 UTC, snailspeed3 commented on source/gamespy/GP/gp.c
> +/*
Let's consider having our own project-wide message at the top.

2021-07-11 12:15 UTC, snailspeed3 commented on source/gamespy/GP/gp.c
> +  if (pProfile->buddyStatus)
Did you forget the semicolons here..?

2021-07-11 12:15 UTC, snailspeed3 commented on source/gamespy/GP/gpiInfo.c
> +  arg->conntypeid = cache->conntypeid;
Haha

2021-07-11 12:15 UTC, riidefi commented on source/gamespy/common/revolution/gsThreadRevolution.c
> +  OSRestoreInterrupts(enabled);
Just a note: there's a better way to do this without disabling interrupts. If we ever wanted to enable multiple WiiU cores, these OSDisableInterrupts calls would get in our way.

2021-07-11 12:15 UTC, riidefi commented on source/gamespy/ghttp/ghttpBuffer.c
> +    bResult = ghiResizeBuffer(buffer, buffer->sizeIncrement);
But what if dataLen > buffer->sizeIncrement..?

2021-07-11 12:15 UTC, riidefi commented on source/gamespy/ghttp/ghttpCommon.c
> +asm GHIRecvResult ghiDoReceive(GHIConnection* connection, char buffer[],
Can you add a NON_MATCHING version of these?

2021-07-11 12:15 UTC, riidefi commented on source/gamespy/qr2/qr2.c
> +asm void qr2_check_queries(qr2_t qrec) {
Add NON_MATCHING version if possible

2021-07-11 12:25 UTC, SeekyCt commented on source/gamespy/ghttp/ghttpBuffer.c
> +    bResult = ghiResizeBuffer(buffer, buffer->sizeIncrement);
Won't it keep increasing by sizeIncrement until it fits or runs out of memory?

2021-07-11 12:33 UTC, riidefi commented on source/gamespy/ghttp/ghttpBuffer.c
> +    bResult = ghiResizeBuffer(buffer, buffer->sizeIncrement);
Yep

2021-07-13 03:28 UTC, wait-wtf commented on source/gamespy/GP/gp.c
> +  if (pProfile->buddyStatus)
Fixed

2021-07-13 03:37 UTC, wait-wtf commented on source/gamespy/ghttp/ghttpCommon.c
> +asm GHIRecvResult ghiDoReceive(GHIConnection* connection, char buffer[],
Added NON_MATCHING version of ghiDoReceive().

2021-07-13 03:37 UTC, wait-wtf commented on source/gamespy/qr2/qr2.c
> +asm void qr2_check_queries(qr2_t qrec) {
Added NON_MATCHING version of qr2_check_queries().

2021-07-13 04:43 UTC, merged

2021-07-13 06:32 UTC, wait-wtf commented
See also: https://github.com/riidefi/mkw/issues/28